# Generated by Django 3.2.15 on 2022-09-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='song_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='song_pop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='song_rock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Approved')], default=0),
        ),
    ]
