# Generated by Django 3.2.15 on 2022-12-04 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20220910_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='song_country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song_pop',
        ),
        migrations.RemoveField(
            model_name='post',
            name='song_rock',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='forumpost_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
